# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
   gulp clean
   gulp bundle --ship
   gulp package-solution --ship
   dir
  displayName: 'Build and Package Solution"
 
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/sharepoint/solution'
    Contents: 'spfx-extensions.sppkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/drop'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
    ArtifactName: 'drop'
    publishLocation: 'Container'
